apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
stringData:
  SECRET_KEY: "mk3gi2gpp1k1rel4k2192mnj210dSAa213kdksapp 123lao1i28aa"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "secretpasswordfordb"
  POSTGRES_DB: "users_db"